spring:
  application:
    name: currency-service

server:
  port: 8085

# ⬇️ API Externa (sin API key, gratuita)
exchangerate:
  api:
    base-url: https://open.er-api.com/v6/latest

# Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

# Resilience4j (Circuit Breaker)
resilience4j:
  circuitbreaker:
    instances:
      currencyApi:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3
  
  retry:
    instances:
      currencyApi:
        max-attempts: 3
        wait-duration: 1s

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Logging
logging:
  level:
    com.huisa: DEBUG
    feign: DEBUG

# Swagger
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
