spring:
  application:
    name: discovery-service

# Configuración del servidor
server:
  port: 8761

# Configuración de Eureka Server
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false  # No se registra a sí mismo
    fetch-registry: false  # No intenta buscar otros servicios
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false  # Desactivar en desarrollo
    eviction-interval-timer-in-ms: 5000  # Limpiar instancias cada 5 segundos

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Logging
logging:
  level:
    com.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG
    com.huisa: INFO
